### PR TITLE
fix: Dehydration of class components

### LINKED ISSUE #1534: Notebooks are empty after Docker container restarts
**Description**

In the last few days, I've had a few instances where I exit and restart my Docker container, only to find the notebook I was working on empty. I only saw it happen for notebooks _not_ in a folder, though I didn't test it with notebooks in folders.

**Steps to reproduce**

Create a notebook, write a simple query, save it, and reload the Docker container.

**Expected results**

The notebook to appear as I was working on it before restarting my container.

**Actual results**

The notebook development panel is empty, despite having text in it previously.

**Additional details and attachments**

**Versions**

 - Engine Version: 0.28.1
 - Web UI Version: ...
 - Java Version: ...
 - Barrage Version: ...
 - OS: OS X
 - Browser: Chrome
 - Docker: 20.10.13

### PR DESCRIPTION
**Pull request by mattrunyon**
Fixes #1534

### CODE REVIEW

File: packages/dashboard/src/DashboardLayout.tsx [hunk 1]
```diff
@@ -118,24 +119,49 @@ export function DashboardLayout({
...
+          about assigning refs to function components not using forwardRef.
+          The ref is used to detect changes to class component state so we
+          can track changes to panelState. We should opt for more explicit
+          state changes in the future and in functional components.
+        */
+        const isClassComponent =
+          (isWrappedComponent(CType) &&
+            CType.WrappedComponent.prototype != null &&
+            CType.WrappedComponent.prototype.isReactComponent != null) ||
+          (CType.prototype != null && CType.prototype.isReactComponent != null);
```
Comment (mofojed) [inline packages/dashboard/src/DashboardLayout.tsx:141]: Gross. Good work!

**Review by mofojed — APPROVED** [review]
Gross

**Review by mofojed — APPROVED** [review]
