### PR TITLE
fix: Preview did not draw correctly when dragging Grids

### LINKED ISSUE #1112: drag proxy preview is broken
**Description**

Dragging a panel used to show a preview of the item while dragging. It should re-render the canvas. It looks like it's only rendering a black square, but for some reason also the selection box? Note this has been broken since bard maybe

image

### PR DESCRIPTION
**Pull request by mofojed**
- When we drag something, there is a frame where the width/height is 0
- We didn't update the metrics within the actual animation frame, so it was drawing the wrong thing
- Fix so metrics are always updated in the animation frame, and also to only check the metrics with the previously checked metrics
- Tested with ticking tables stuck to the bottom to ensure they stuck while ticking
- Fixes #1112

### CODE REVIEW

File: packages/grid/src/Grid.tsx [hunk 1]
```diff
@@ -850,6 +832,37 @@ class Grid extends PureComponent<GridProps, GridState> {
     }
   }
 
+  checkMetricsUpdates() {
```
Comment (mattrunyon) [inline packages/grid/src/Grid.tsx:835]: Can you add a comment for why you would call this method over `updateMetrics`? Seems this is actually just scrolling sticky tables. If that's the case, update the method name to be more clear. `scrollIfSticky` maybe?

**Review by mattrunyon — CHANGES_REQUESTED** [review]

**Review by mattrunyon — APPROVED** [review]
