### PR TITLE
fixed unable to open csv

### LINKED ISSUE #675: Import CSV throws an error after submitting
**Description**

**Steps to reproduce**
1. Drag and drop a csv file onto the Console (can use https://github.com/deephaven/examples/blob/main/StandardAndPoors500Financials/csv/s_and_p_500_companies_financials.csv for example)
2. Click on Upload

**Expected results**

2. CSV file uploads, no error

**Actual results**

2. An exception is thrown, and the console panel errors out:
```
Uncaught Error: Value is null or undefined
    at assertNotNull (Asserts.ts:5:1)
    at disableOldObject (Console.tsx:512:1)
    at Console.tsx:532:1
    at Array.forEach (<anonymous>)
    at Console.<anonymous> (Console.tsx:532:1)
    at getStateFromUpdate (react-dom.development.js:12102:1)
    at processUpdateQueue (react-dom.development.js:12250:1)
    at updateClassInstance (react-dom.development.js:13013:1)
    at updateClassComponent (react-dom.development.js:17432:1)
    at beginWork (react-dom.development.js:19073:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at scheduleUpdateOnFiber (react-dom.development.js:21893:1)
    at Object.enqueueSetState (react-dom.development.js:12467:1)
    at push.../../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:365:1)
    at Console.updateKnownObjects (Console.tsx:496:1)
    at Console.handleOpenCsvTable (Console.tsx:728:1)
    at CsvInputBar.openTable (CsvInputBar.tsx:277:1)
    at CsvInputBar.tsx:187:1
```

image

### PR DESCRIPTION
**Pull request by SparkyFnay**
Fixes #675 
Note that the `name` property on the object with type `VariableChange` is deprecated, the correct value should be stored in `title`. So instead of reverting `title` back to `name`, I added the object with a `title` property when it's created in `handleOpenCsvTable`

### CODE REVIEW

File: packages/console/src/Console.tsx [hunk 1]
```diff
@@ -535,10 +535,10 @@ export class Console extends PureComponent<ConsoleProps, ConsoleState> {
       // Created objects have to be processed after removed
       // in case the same object name is present in both removed and created
       changes?.created.forEach(object => {
-        const { title } = object;
-        assertNotNull(title);
-        objectHistoryMap.set(title, itemIndex);
-        objectMap.set(title, object);
+        const { name } = object;
```
Comment (mofojed) [inline packages/console/src/Console.tsx:538]: As you mentioned, `name` is deprecated, you should still be using `title` here.

**Review by mofojed — CHANGES_REQUESTED** [review]

**Review by mofojed — APPROVED** [review]
