### PR TITLE
fix: makeApiContextWrapper and createMockProxy

### LINKED ISSUE #1311: TestUtils - makeApiContextWrapper console error and mock proxy improvements
- makeApiContextWrapper currently shows a console error due to ApiContextWrapper not being wrapped in forwardRef
- The proxy created by createMockProxy prints `undefined` when used in matchers. This could use some cleanup

### PR DESCRIPTION
**Pull request by bmingles**
- makeApiContextWrapper - wrapped in forwardRef to remove console.errr
- createMockProxy - now prints object properties instead of `undefined` in jest matchers. Proxied mock methods now include a mockName() call to give clearer output

fixes #1311

### CODE REVIEW

File: packages/jsapi-components/src/HookTestUtils.tsx [hunk 1]
```diff
@@ -1,11 +1,18 @@
...
-export function makeApiContextWrapper(dh: DhType) {
-  return function ApiContextWrapper({ children }: { children?: ReactNode }) {
+export function makeApiContextWrapper<TProps, TRef = unknown>(dh: DhType) {
+  return forwardRef<TRef, TProps>(function ApiContextWrapper(
+    {
+      children,
+    }: {
+      children?: ReactNode;
+    },
+    _ref
```
Comment (vbabich) [inline packages/jsapi-components/src/HookTestUtils.tsx:12]: I wonder what's the root cause of the issue? Why does `renderHook` require the ref? `_ref` argument isn't even passed anywhere, could this be a bug in `renderHook` itself?

Comment (bmingles) [reply packages/jsapi-components/src/HookTestUtils.tsx:12]: I suspect it uses it internally for something but not sure

Comment (bmingles) [reply packages/jsapi-components/src/HookTestUtils.tsx]: nvm, I was wrong. Real cause of the original issue is that `ref` needs to be excluded from the auto proxy

**Review by vbabich — APPROVED** [review]
