### PR TITLE
Golden layout fallback for unregistered components

### LINKED ISSUE #184: Implement fallback for unregistered components in GoldenLayout
GoldenLayout currently throws an error and fails to render the layout with a config that contains unregistered components.
We should be able to specify a fallback component that would render in place of the unregistered components.

### PR DESCRIPTION
**Pull request by vbabich**
Fixes #184

### CODE REVIEW

File: packages/golden-layout/src/js/utils/ReactComponentHandler.js [hunk 1]
```diff
@@ -13,6 +13,7 @@ lm.utils.ReactComponentHandler = function (container, state) {
   this._container = container;
   this._initialState = state;
   this._reactClass = this._getReactClass();
+  console.log('ReactComponentHandler', this._reactClass, container, state);
```
Comment (mofojed) [inline packages/golden-layout/src/js/utils/ReactComponentHandler.js:16]: Remove extra console.log

File: packages/golden-layout/src/js/LayoutManager.js [hunk 2]
```diff
@@ -209,15 +222,21 @@ lm.utils.copy(lm.LayoutManager.prototype, {
    * @returns {Function}
    */
   getComponent: function (name) {
-    if (this._components[name] === undefined) {
-      throw new lm.errors.ConfigurationError(
-        'Unknown component "' + name + '"'
-      );
-    }
-
+    console.log('getComponent', name);
```
Comment (mofojed) [inline packages/golden-layout/src/js/LayoutManager.js:225]: Remove console.log

File: packages/code-studio/src/dashboard/DashboardContainer.jsx [hunk 3]
```diff
@@ -56,29 +57,6 @@ const log = Log.module('DashboardContainer');
 const RESIZE_THROTTLE = 100;
 
 export class DashboardContainer extends Component {
-  static dehydratePanelConfig(config) {
```
Comment (mofojed) [inline packages/code-studio/src/dashboard/DashboardContainer.jsx:59]: I think I did something similar in my separating dashboards branch (moving dehydratePanelConfig to LayoutUtils)

**Review by mofojed — CHANGES_REQUESTED** [review]
Great stuff, just remove the `console.log` statements and it should be good.
