### PR TITLE
Fix broken conditional formatting sidebar

### LINKED ISSUE #676: Conditional formatting broken
Open table sidebar on a table, and go to add a conditional formatting rule. Fails immediately with:

LogProxy.ts:82 Error: Value is null or undefined
    at wt (Asserts.ts:5:28)
    at IrisGrid.tsx:3697:11
    at Array.map (<anonymous>)
    at n.value (IrisGrid.tsx:3664:42)

### PR DESCRIPTION
**Pull request by dsmmcken**
Allow rule to be undefined, as that is how an empty rule is initialized. Fixes #676.

### CODE REVIEW

File: packages/iris-grid/src/IrisGrid.tsx [hunk 1]
```diff
@@ -353,7 +353,7 @@ export interface IrisGridState {
 
   conditionalFormats: SidebarFormattingRule[];
   conditionalFormatEditIndex: number | null;
-  conditionalFormatPreview?: SidebarFormattingRule | null;
+  conditionalFormatPreview?: SidebarFormattingRule | undefined;
```
Comment (mofojed) [inline packages/iris-grid/src/IrisGrid.tsx:356]: This is redundant, the `?` already implies `undefined`:
```suggestion
  conditionalFormatPreview?: SidebarFormattingRule;
```

File: packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormatEditor.tsx [hunk 2]
```diff
@@ -24,7 +24,7 @@ export type CancelCallback = () => void;
 
 export interface ConditionalFormatEditorProps {
   columns: ModelColumn[];
-  rule?: FormattingRule;
+  rule?: FormattingRule | undefined;
```
Comment (mofojed) [inline packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormatEditor.tsx:27]: Redundant
```suggestion
  rule?: FormattingRule;
```

**Review by mofojed — CHANGES_REQUESTED** [review]

**Review by mofojed — APPROVED** [review]
