### PR TITLE
fix: add back panel prop to IrisGrid Plugin

### LINKED ISSUE #2093: TablePlugin needs to know current grid selection, table name
As a developer of a TablePlugin, I would like to be able to get the table name and the current selection state from within my plugin.
Previously we could do this with the `panel` prop that was passed in before it was removed: https://github.com/deephaven/web-client-ui/pull/1982
Could use `panel.getTableName()` to get the table name and `panel.irisGrid.current.state` to get the selected range of rows. Would like to still be able to do that.

### PR DESCRIPTION
**Pull request by AkshatJawne**
Closes #2093  (For now, will reopen ticket after merge for better solution to handle deprecated `panel` prop)

### CODE REVIEW

File: packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx [hunk 1]
```diff
@@ -423,6 +423,11 @@ export class IrisGridPanel extends PureComponent<
         return null;
       }
 
+      // TODO: Find a better way to handle deprecated panel prop
```
Comment (mofojed) [inline packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx:426]: For a TODO like this, we should reference a ticket number and have a ticket created. We can clone the current ticket, or just use the same ticket since this is kind of an interim solution. We want something better.

```suggestion
      // TODO #2096: Find a better way to handle deprecated panel prop
```

**Review by mofojed — CHANGES_REQUESTED** [review]

**Comment by AkshatJawne** [comment]
Added current ticket number in TODO comment, and updated description to indicate that ticket will reopen after this merge to look at a more long-term, proper solution.

**Review by mofojed — APPROVED** [review]
