### PR TITLE
fix: cap width of columns with long names

### LINKED ISSUE #1276: Long column names should be truncated to a maximum width by default (but still resizeable)
**Description**
Related to #1283 

When creating a column with a very long name, the column name is cut off on the right of the table panel if it is the last column in the table.

**Steps to reproduce**
Run the following code:
```
from deephaven import new_table
from deephaven.column import string_col, int_col

result = new_table([
    int_col("I1", [1, 2, 3]),
    int_col("I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I23", [4, 5, 6]),
])
```
**Expected results**
1. The column has a maximum width by default (600px?) and column header is truncated by default

**Actual results**

1. The column name is cut off (Note the absent 3 in the screenshot below)

**Additional details and attachments**

Screenshot 2023-05-08 at 3 01 58 PM

**Versions**

Engine Version: 0.24.0
Web UI Version: 0.34.0
Java Version: 11.0.17
Barrage Version: 0.5.0

### PR DESCRIPTION
**Pull request by ethanalvizo**
Closes #1276 

Use the following command to test a table with a long column name
```
from deephaven import new_table
from deephaven.column import string_col, int_col

result = new_table([
    int_col("I1", [1, 2, 3]),
    int_col("I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I2I23", [4, 5, 6]),
])
```

New table render with capped column width
image

### CODE REVIEW

**Comment by dsmmcken** [comment]
image

Shouldn't it be based on available space?

File: packages/grid/src/GridMetricCalculator.ts [hunk 1]
```diff
@@ -1043,7 +1043,7 @@ export class GridMetricCalculator {
         firstColumn,
         treePaddingX
       );
-      columnWidths.set(column, columnWidth);
+      columnWidths.set(column, Math.min(600, columnWidth));
```
Comment (mofojed) [inline packages/grid/src/GridMetricCalculator.ts:1046]: We want this constant to be defined in the theme so it can be changed manually if needed. Take a look at the `calculateColumnWidth` method - we already have a `minColumnWidth`, we could just define a `maxColumnWidth` that it uses and never go over that.
Note this doesn't address https://github.com/deephaven/web-client-ui/issues/1284, but that's fine and can be addressed in a separate PR.

**Review by mofojed — CHANGES_REQUESTED** [review]

File: packages/grid/src/GridMetricCalculator.ts (hunk 1 above)
Comment (ethanalvizo) [reply packages/grid/src/GridMetricCalculator.ts:1046]: I can take on #1284 after this one. I think it'll be somewhat related anyways

**Review by mofojed — APPROVED** [review]
