### PR TITLE
iris-grid displays null instead of empty when fast scrolling for string columns

### LINKED ISSUE #630: Scrolling fast in grid flashes null for string values
**Description**

When scrolling quickly such that more data must be fetched, the values are showing as null until fetched instead of empty (previous behavior). These seems to affect string columns specifically.

**Steps to reproduce**
1. Run either of these Python snippets

```python
from deephaven import empty_table
t = empty_table(100000).update_view(["x=`A`"])
```

```python
from deephaven import new_table
from deephaven.column import string_col, char_col, int_col

table = new_table([
    string_col("Short", ["A" , "B", "C", "D"]),
    char_col("Char", "ABCD"),
    int_col("Int", [123456789, 234567890, 42, 8675309]),
    string_col("Short2", ["A" , "B", "C", "D"]),
    char_col("Char2", "ABCD"),
    int_col("Int2", [123456789, 234567890, 42, 8675309]),
    string_col("Short3", ["A" , "B", "C", "D"]),
    char_col("Char3", "ABCD"),
    int_col("Int3", [123456789, 234567890, 42, 8675309]),
    string_col("Short4", ["A" , "B", "C", "D"]),
    char_col("Char4", "ABCD"),
    int_col("Int4", [123456789, 234567890, 42, 8675309]),
    string_col("Short5", ["A" , "B", "C", "D"]),
    char_col("Char5", "ABCD"),
    int_col("Int5", [123456789, 234567890, 42, 8675309]),
    string_col("Short6", ["A" , "B", "C", "D"]),
    char_col("Char6", "ABCD"),
    int_col("Int6", [123456789, 234567890, 42, 8675309]),
    string_col("Short7", ["A" , "B", "C", "D"]),
    char_col("Char7", "ABCD"),
    int_col("Int7", [123456789, 234567890, 42, 8675309]),
    string_col("Short8", ["A" , "B", "C", "D"]),
    char_col("Char8", "ABCD"),
    int_col("Int8", [123456789, 234567890, 42, 8675309]),
    string_col("Short9", ["A" , "B", "C", "D"]),
    char_col("Char9", "ABCD"),
    int_col("Int9", [123456789, 234567890, 42, 8675309]),
    string_col("Short10", ["A" , "B", "C", "D"]),
    char_col("Char10", "ABCD"),
    int_col("Int10", [123456789, 234567890, 42, 8675309]),
    string_col("Short11", ["A" , "B", "C", "D"]),
    char_col("Char11", "ABCD"),
    int_col("Int11", [123456789, 234567890, 42, 8675309]),
    string_col("Short12", ["A" , "B", "C", "D"]),
    char_col("Char12", "ABCD"),
    int_col("Int12", [123456789, 234567890, 42, 8675309]),
])
```
3. Scroll quickly by dragging the scroll bar to the ends

**Expected results**

4. Empty display until data is fetched (short flash of empty values)

**Actual results**

4. All values flash as null and not the stylized null

**Additional details and attachments**

Video of horizontal issue
https://user-images.githubusercontent.com/8619789/176281255-bbb2d053-499b-4f98-ba53-1380bc5a5cea.mov

**Versions**
 - Deephaven: 0.14

### PR DESCRIPTION
**Pull request by SparkyFnay**
Fixes #630

### CODE REVIEW

File: packages/iris-grid/src/IrisGridTableModelTemplate.ts [hunk 1]
```diff
@@ -697,12 +697,12 @@ class IrisGridTableModelTemplate<
...
 
-  valueForCell(x: ModelIndex, y: ModelIndex): unknown | null {
+  valueForCell(x: ModelIndex, y: ModelIndex): unknown | null | undefined {
     const data = this.dataForCell(x, y);
     if (data) {
       return data.value ?? null;
     }
-    return null;
+    return undefined;
   }
```
Comment (mofojed) [inline packages/iris-grid/src/IrisGridTableModelTemplate.ts:706]: Should also be returning `undefined` in the `if` case as well.

I think this whole method could just be written like:
```
  valueForCell(x: ModelIndex, y: ModelIndex): unknown | null | undefined {
    return this.dataForCell(x, y)?.value;
  }
```

Comment (mattrunyon) [reply packages/iris-grid/src/IrisGridTableModelTemplate.ts:706]: Oh I remember the reason (and please add this as a code comment)

The JS API currently sets null values as undefined in some instances. This means we need to nullish coaelesce so all undefined values from the API return `null` since the data has been fetched. `undefined` is used to indicate the API has not fetched data yet

Comment (mofojed) [reply packages/iris-grid/src/IrisGridTableModelTemplate.ts]: Good catch. I was looking at an older code branch before that fix, my bad.

**Review by mofojed — APPROVED** [review]
