### PR TITLE
Fix Some Shortcut Problems

### LINKED ISSUE #142: Various issues with keyboard shortcuts.
**Description**

Some of the expected keyboard shortcuts are not working as expected. 
These manifest differently between windows and macos. 

I found these on Deephaven Enterprise but will effect OSS as well. 

**Windows**
Ctrl + L 
Expected clear console. Actually brings up linking tool. 

Ctrl + H  when history tab is not active
Expected history tab becomes active and gets focus. Actually nothing happens. 

Delete when file explorer tab is active
Expected delete notebook dialog. Actually delete command is entered into currently active notebook. 

Enter when file explorer tab is active
Expected change name dialog. Actually enter command is entered into currently active notebook. 

Ctrl + S on Input Table
Expected commit changes. Actually brings up search bar. 

Ctrl + E
Expected clear all table filters on all tables. Actually moves focus to title bar.

**MacOs**

Control + C
Expected clearing console history. Actually nothing happens. 

Cmd + Shift + E
Expected clearing filters on currently active table. Actually all filters on all tables are cleared. 

Cmd + S on Input table
Expected to commit input table changes. Actually toggles search bar. 

Cmd + E 
Expected clear all table filters on all tables. Actually highlights Edit but no action is preformed. 

**Versions**
 - Deephaven Enterprise: 1.20210201.147beta
 - Web Browser: crhome

### PR DESCRIPTION
**Pull request by mattrunyon**
Fixes #142 (mostly). See #151 which will address remaining shortcut problems.

Removes the global shortcut handlers from being attached to the capture phase instead of bubble phase. This makes local shortcuts take precedence over global shortcuts. Also means linker won't trigger when inside of monaco, but monaco has its own shortcuts and Don said we should just leave monaco shortcuts alone instead of removing them so our shortcuts work globally (really it's only linker)

### CODE REVIEW

File: packages/code-studio/src/main/AppControlsMenu.jsx [hunk 1]
```diff
@@ -169,7 +169,7 @@ const AppControlsMenu = props => {
           onClearFilter();
         },
         order: 60,
-        shortcut: GRID_SHORTCUTS.TABLE.CLEAR_FILTERS,
+        shortcut: GRID_SHORTCUTS.TABLE.CLEAR_ALL_FILTERS,
```
Comment (mofojed) [inline packages/code-studio/src/main/AppControlsMenu.jsx:172]: It bugs me that you named it `GRID_SHORTCUTS` here, but `IRIS_GRID_SHORTCUTS` in AppMainContainer. Would like it to be consistent.

**Review by mofojed — APPROVED** [review]

**Review by mofojed — CHANGES_REQUESTED** [review]
You'll need to fix that failing test

**Review by mofojed — APPROVED** [review]
