### PR TITLE
DH-10111 Fix missing horizontal scroll bar for single column tables

### LINKED ISSUE #446: Horizontal scroll never appears for single column table
**Description**

With a single column table, it is not possible to trigger the horizontal scroll bar even if the column extends past the edge of the container

**Steps to reproduce**
1. Create a single column table
```python
from deephaven.TableTools import newTable, stringCol

source = newTable(
    stringCol("Long", "A"*50),
)
```
2. Resize such that the column extends past the edge of the container

**Expected results**

Horizontal scroll appears

**Actual results**

No horizontal scroll

**Additional details and attachments**

This only appears to be a problem for tables w/ 1 column. I believe the problem is in `GridMetricCalculator` specifically where `hasHorizontalBar` is calculated. This also technically affects tables w/ a single row and vertical scroll probably, but a panel smaller than a row's height is pretty useless to scroll

**Versions**
 - Deephaven: 0.9.3

### PR DESCRIPTION
**Pull request by mattrunyon**
Fixes #446 and related to DH-10111 test failure

This adds a horizontal scroll bar for any single column table which does not fit in the panel fully

Example Python to test with
```python
from deephaven import new_table
from deephaven.column import string_col
import random
import string

letters = string.printable
strings = [''.join(random.choice(letters) for i in range(random.randint(0, 1000))) for j in range(0, 100)]
table1 = new_table([string_col("Random", strings)])
```

Also tested with changing `IrisGridTheme.rowHeaderWidth` to be non-zero

### CODE REVIEW

File: packages/grid/src/GridMetricCalculator.ts [hunk 1]
```diff
@@ -319,47 +325,54 @@ export class GridMetricCalculator {
...
-      lastTop > 0
-        ? Math.min(
-            Math.max(
-              minScrollHandleSize,
-              barHeight * ((rowCount - lastTop) / rowCount)
-            ),
-            barHeight - 1
-          )
-        : 0;
+    // How big the horizontal is relative to the horizontal bar
```
Comment (mofojed) [inline packages/grid/src/GridMetricCalculator.ts:335]: We should be doing this for both horizontal and vertical scroll bars. Row height can be resized to be larger than the viewport as well (though not a use case we currently have).

**Review by mofojed — CHANGES_REQUESTED** [review]
Shift+Wheel (which should scroll horizontally) isn't working. I think need to update Grid.tsx `handleWheel` function

File: packages/grid/src/GridMetricCalculator.ts (hunk 1 above)
Comment (mattrunyon) [reply packages/grid/src/GridMetricCalculator.ts:335]: We are doing this for vertical bar currently, I just didn't rename it like I did horizontal. Do you want me to rename vertical too so it's more clear?

**Comment by mattrunyon** [comment]
Updated so vertical scroll uses the same logic as horizontal

Tested by setting a big `rowHeight` in `IrisGridTheme.module.scss`. Also fixed/tested horizontal scroll with `scrollSnapToColumn: true` in `IrisGridTheme.ts`
