### PR TITLE
Fix broken advanced filter creator

### LINKED ISSUE #648: Unable to open Advanced Filter dialog
**Description**

The app throws an exception when trying to open Advanced Filter on a table column.

**Steps to reproduce**
1. Run this command in the console to create a table:
```
from deephaven.TableTools import emptyTable
t = emptyTable(10).update("x = i")
```
2. Click on any value in the `x` column to focus the table.
3. Press `Cmd+F` to show the filter bar, click on the Funnel icon to open the Advanced filter dialog:
Screen Shot 2022-07-12 at 10 16 47 AM

**Expected results**

Advanced filter dialog shows up.

**Actual results**

The Advanced Filter dialog doesn't show up, the app throws an exception in the browser console:
```
AdvancedFilterCreator.tsx:129 Uncaught TypeError: Cannot read properties of null (reading 'map')
    at new AdvancedFilterCreator (AdvancedFilterCreator.tsx:129:1)
    at constructClassInstance (react-dom.development.js:12716:1)
    at updateClassComponent (react-dom.development.js:17425:1)
    at beginWork (react-dom.development.js:19073:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at scheduleUpdateOnFiber (react-dom.development.js:21893:1)
    at Object.enqueueSetState (react-dom.development.js:12467:1)
    at push.../../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:365:1)
    at Popper.initPopper (Popper.tsx:178:1)
    at Popper.show (Popper.tsx:204:1)
    at Popper.tsx:106:1
```

**Versions**
 - Deephaven: 0.14.1

### PR DESCRIPTION
**Pull request by dsmmcken**
Broke from typescript migration. Fixes #648.

- Allow filterCondition to be null, it is used to clear filters and fix things that break due to that
- Make value list still show if table is not yet set, so that it reserves space rather than pop in.

### CODE REVIEW

File: packages/iris-grid/src/AdvancedFilterCreator.tsx [hunk 1]
```diff
@@ -592,19 +588,17 @@ class AdvancedFilterCreator extends PureComponent<
...
-                    selectedValues={selectedValues}
-                    formatter={formatter}
-                    showSearch={!isDateType}
-                    timeZone={formatter.timeZone}
-                  />
-                </div>
-              )}
+              <div className="form-group">
+                <AdvancedFilterCreatorSelectValue<unknown>
+                  table={valuesTable}
```
Comment (mofojed) [inline packages/iris-grid/src/AdvancedFilterCreator.tsx:593]: This should be giving you an error - you're passing in `valuesTable`, which could be `Table | undefined`... in `AdvancedFilterCreatorSelectValue` and `AdvancedFilterCreatorSelectValueList` table is a required prop. 

The problem is in `AdvancedFilterCreatorSelectValue` and `AdvancedFilterCreatorSelectValueList`, where we're assigning a defaultProp of `table: null`. I think what you _want_ is for those props to be optional (`table?: Table`), don't define the defaultProp, then leave this like it is here.

**Review by mofojed — CHANGES_REQUESTED** [review]

File: packages/iris-grid/src/AdvancedFilterCreator.tsx [hunk 2]
```diff
@@ -121,19 +121,17 @@ class AdvancedFilterCreator extends PureComponent<
...
-      ({ selectedType, value }) => ({
+    let filterItems: AdvancedFilterItem[] =
+      options.filterItems?.map(({ selectedType, value }) => ({
         selectedType,
         value,
         key: shortid(),
-      })
-    );
-    if (filterItems == null) {
+      })) ?? [];
```
Comment (SparkyFnay) [inline packages/iris-grid/src/AdvancedFilterCreator.tsx:133]: `let filterItems: AdvancedFilterItem[] =
      options.filterItems?.map(({ selectedType, value }) => ({
        selectedType,
        value,
        key: shortid(),
      })) ?? [AdvancedFilterCreator.makeFilterItem()];`

Then you don't need thee `filterItems.length === 0` check

Comment (SparkyFnay) [reply packages/iris-grid/src/AdvancedFilterCreator.tsx:133]: this

**Review by SparkyFnay — CHANGES_REQUESTED** [review]

**Comment by dsmmcken** [comment]
The and/or behaviour was broken entirely and appears to have been broken in jackson too? I think this fixes it.

File: packages/iris-grid/src/AdvancedFilterCreator.tsx (hunk 2 above)
Comment (dsmmcken) [reply packages/iris-grid/src/AdvancedFilterCreator.tsx:134]: Tried, but actually while it can be initialized as null, but if you set something then remove it, then next time it is initialized as [], so you still need the === 0 check.

**Review by mofojed — CHANGES_REQUESTED** [review]
There's still an issue in `AdvancedFilterCreatorFilterItem`, not caused by your change but I'm unable to change advanced filter type.

This diff fixes it:
```
diff --git a/packages/iris-grid/src/AdvancedFilterCreatorFilterItem.tsx b/packages/iris-grid/src/AdvancedFilterCreatorFilterItem.tsx
index a79c466df..e962def66 100644
--- a/packages/iris-grid/src/AdvancedFilterCreatorFilterItem.tsx
+++ b/packages/iris-grid/src/AdvancedFilterCreatorFilterItem.tsx
@@ -78,21 +78,20 @@ export class AdvancedFilterCreatorFilterItem extends PureComponent<
   }
 
   componentDidUpdate(prevProps: AdvancedFilterCreatorFilterItemProps): void {
-    const {
-      value = '',
-      filterTypes,
-      selectedType = filterTypes[0],
-    } = this.props;
-    if (prevProps.selectedType !== selectedType || prevProps.value !== value) {
-      this.setState({ selectedType, value });
+    const { value, selectedType } = this.props;
+    if (selectedType !== undefined && prevProps.selectedType !== selectedType) {
+      this.setState({ selectedType });
+    }
+    if (value !== undefined && prevProps.value !== value) {
+      this.setState({ value });
     }
   }
 
   typeDropdown: HTMLSelectElement | null;
 
   handleTypeChange(event: React.ChangeEvent<HTMLSelectElement>): void {
-    log.debug2('typeChange');
     const selectedType = event.target.value as FilterTypeValue;
+    log.debug2('typeChange', selectedType);
     this.setState({ selectedType });
 
     const { onChange } = this.props;
```

**Review by SparkyFnay — DISMISSED** [review]

**Review by mofojed — APPROVED** [review]
