### PR TITLE
Fix scrollbars drawing without handles when grid is the perfect size

### LINKED ISSUE #561: Vertical scroll bar can be drawn without handle
**Description**

If the table is sized just right, the vertical scroll track is drawn, but not the handle. This occurs if the last row of the table goes under the horizontal scroll bar.

image

**Steps to reproduce**
1. Create a table with only a few rows such as this Python
```python
from deephaven import new_table
from deephaven.column import string_col, char_col, int_col

table = new_table([
    string_col("Short", ["A" , "B", "C", "D"]),
    string_col("Long", ["A"*50 , "B"*500, "C"*5000, "D"*49900]),
    char_col("Char", "ABCD"),
    int_col("Int", [123456789, 234567890, 42, 8675309]),
])
```
2. Shrink to where the horizontal scroll bar appears.
3. Shrink vertically until the last row is just under the horizontal scroll bar.

**Expected results**

Both scroll bars fully appear

**Actual results**

Vertical scroll track appears, but not the handle

**Versions**
 - Deephaven: 0.11.9

### PR DESCRIPTION
**Pull request by mattrunyon**
Fixes #561

### CODE REVIEW

File: packages/grid/src/GridMetricCalculator.ts [hunk 1]
```diff
@@ -803,7 +819,7 @@ export class GridMetricCalculator {
       lastLeft = right;
     }
     let x = 0;
-    while (lastLeft > 0) {
+    while (lastLeft >= 0) {
```
Comment (mofojed) [inline packages/grid/src/GridMetricCalculator.ts:822]: This is reverting your fix from https://github.com/deephaven/web-client-ui/pull/940, and that problem is now back. Need some way to handle that case.

**Review by mofojed — CHANGES_REQUESTED** [review]

**Review by mofojed — APPROVED** [review]
