### PR TITLE
Fix incorrect table sizes in panel tab tooltip

### LINKED ISSUE #820: Web console reports incorrect table sizes in panel tab tooltip when table is changing sizes
Running 'latest' at 7dd6468139ffc0234c72236107f4b51354c4f581

My query is
```
from deephaven import time_table
test1 = time_table("00:00:00.000001").update_view(["Int64Value = ii"]).tail(3000000)
```

Expected value for 'Number of Rows': 3,000,000. Displayed value: 1.

image

Using up-arrow to run the same query but store it in `test2`
```
test2 = time_table("00:00:00.000001").update_view(["Int64Value = ii"]).tail(3000000)
```

Now `test1` has the correct count but `test2` has the incorrect count:
image
image

If I do the same thing with `test3`, then `test2` will have the correct count and `test3` will be wrong. And so on.

### PR DESCRIPTION
**Pull request by jason-wang24**
Fixes #820

### CODE REVIEW

File: packages/dashboard-core-plugins/src/panels/IrisGridPanelTooltip.tsx [hunk 1]
```diff
@@ -0,0 +1,47 @@
+import React, { ReactElement, useEffect, useState } from 'react';
```
Comment (mofojed) [inline packages/dashboard-core-plugins/src/panels/IrisGridPanelTooltip.tsx:1]: `useEffect`, `useState` unused
```suggestion
import React, { ReactElement } from 'react';
```

**Review by mofojed — CHANGES_REQUESTED** [review]

**Review by mofojed — APPROVED** [review]
