### PR TITLE
Fix default layout init

### LINKED ISSUE #653: Code studio fails to launch on a fresh start
**Description**

Code studio fails to launch when starting in a fresh browser w/ no workspace data

**Steps to reproduce**
1. Launch code studio in a browser without any local data storage

**Expected results**

Launches the default layout

**Actual results**

Fails to launch

**Additional details and attachments**

Likely related to #634 

**Versions**
 - Deephaven: 0.14

### PR DESCRIPTION
**Pull request by mattrunyon**
Fixes #653 

Start in incognito or a separate browser profile.
Open dev tools, go to Application tab.
On storage panel, click "Clear site data"
Reload page. App should load properly

### CODE REVIEW

File: packages/code-studio/src/storage/WebdavLayoutStorage.ts [hunk 1]
```diff
@@ -1,5 +1,5 @@
 import { FileStat, WebDAVClient } from 'webdav/web';
-import LayoutStorage, { ExportedLayout } from './LayoutStorage';
+import LayoutStorage, { ExportedLayout } from '../main/LayoutStorage';
```
Comment (mofojed) [inline packages/code-studio/src/storage/WebdavLayoutStorage.ts:2]: Move `LayoutStorage` to the `storage` folder as well

**Review by mofojed — CHANGES_REQUESTED** [review]
