### PR TITLE
Fixes command history not scrolled to bottom on load

### LINKED ISSUE #859: Command history not scrolled to bottom on load
1. When command history is loaded in as the panel in the background, it loads scrolled to top rather than bottom as expected. If the command history tab is on front when loaded, it loads correctly scrolled to bottom.
  command_history_bug_1

2. If the command history tab is picked up and dropped in place, it's contents disappear until scrolled again. 
  command_history_bug

### PR DESCRIPTION
**Pull request by dsmmcken**
Resolves #859

- Use initialScrollOffset prop to set initial position instead of scrolling to bottom in did mount (which doesn't work when in a backgrounded tab)
- forceUpdate the virtualized list when it is picked up and dropped in the same place

### CODE REVIEW

File: packages/components/src/ItemList.tsx [hunk 1]
```diff
@@ -181,26 +181,19 @@ export class ItemList<T> extends PureComponent<
...
+    const { selectedRanges: propSelectedRanges, itemCount } = this.props;
     const {
       focusIndex,
       isStuckToBottom,
       scrollOffset,
       height,
       selectedRanges,
     } = this.state;
-    if (isStuckToBottom && !this.isListAtBottom()) {
+    if (isStuckToBottom && !this.isListAtBottom() && itemCount > 0) {
```
Comment (mofojed) [inline packages/components/src/ItemList.tsx:196]: I think we still need the `componentDidMount` - if you have a virtual list that's stuckToBottom and has items already loaded, it won't scroll to bottom.

File: packages/dashboard-core-plugins/src/panels/CommandHistoryPanel.tsx [hunk 2]
```diff
@@ -105,6 +106,11 @@ class CommandHistoryPanel extends Component<
     }
   }
 
+  handleShow(): void {
+    // virtual list requires a force re-render when picked up and dropped in same place
+    this.container.current?.update();
```
Comment (mofojed) [inline packages/dashboard-core-plugins/src/panels/CommandHistoryPanel.tsx:111]: Does show always get called in this case? What about listening to `onResize` instead?

**Review by mofojed — CHANGES_REQUESTED** [review]

**Comment by dsmmcken** [comment]
Todo: doesn't always reset correctly on pick up and place back if you scroll first

File: packages/components/src/ItemList.tsx (hunk 1 above)
Comment (mofojed) [reply packages/components/src/ItemList.tsx:196]: I could be wrong, I just tried this by modifying the styleguide and doesn't seem to be an issue. Must be something causing a re-render on mount

Comment (dsmmcken) [reply packages/components/src/ItemList.tsx:196]: I don't think it's needed, that's what the initialScrollOffset is for. when it mounts?

File: packages/dashboard-core-plugins/src/panels/CommandHistoryPanel.tsx (hunk 2 above)
Comment (dsmmcken) [reply packages/dashboard-core-plugins/src/panels/CommandHistoryPanel.tsx:111]: show is enough

File: packages/console/src/command-history/CommandHistory.tsx [hunk 3]
```diff
@@ -351,6 +354,10 @@ class CommandHistory extends Component<
     }
   }
 
+  update(): void {
```
Comment (mattrunyon) [inline packages/console/src/command-history/CommandHistory.tsx:357]: I'd prefer this to be named something else. It's not an update, it's on show or scroll to bottom

File: packages/components/src/ItemList.tsx [hunk 4]
```diff
@@ -324,6 +317,15 @@ export class ItemList<T> extends PureComponent<
     this.listContainer.current?.focus();
   }
 
+  update(): void {
```
Comment (mattrunyon) [inline packages/components/src/ItemList.tsx:320]: Same about naming this `scrollToBottom` instead of `update`

**Review by mattrunyon — CHANGES_REQUESTED** [review]

**Review by mofojed — APPROVED** [review]

**Comment by mattrunyon** [comment]
@dsmmcken Did you fix the position when dropping it in the same position?

**Comment by dsmmcken** [comment]
> @dsmmcken Did you fix the position when dropping it in the same position?

Yes, that's why I added the restoreScrollPosition function

**Review by mattrunyon — APPROVED** [review]
