### PR TITLE
fix: Handle undefined DashboardData props

### LINKED ISSUE #1684: ConsolePanel should not render if there is no session
**Description**

The `ConsolePanel` component has a connect prop to `sessionWrapper`. If this prop is undefined / null, the component crashes when attempting to destructure the prop with an error "Cannot destructure property 'config' of 'sessionWrapper'". This component should not be rendered at all if `sessionWrapper` is undefined.

**Steps to reproduce**

- Run DHC such that it requires PSK for login
- Login
- Open a file (this seems to be necessary to fail the logout. See https://github.com/deephaven/web-client-ui/issues/1685 for related issue)
- Logout

**Expected results**

There should be no console errors. Console should not be rendered if no session is available

**Actual results**

On login there is a console error "Cannot destructure property 'config' of 'sessionWrapper'". On logout, the same error occurs.

**Additional details and attachments**

image

**Versions**

Engine Version: 0.31.0-SNAPSHOT
Web UI Version: 0.56.0
Java Version: 21.0.1
Barrage Version: 0.6.0

### PR DESCRIPTION
**Pull request by bmingles**
- Handle undefined props on DashboardData. Don't render console panel if no session
- Fixed a set state on unmounted HeapUsage bug
- Removed chatty async interval debug logging

fixes #1684

**Testing**
- Run server with PSK enabled
- Login and open any file
- Logout should no longer show "ConsolePanel.tsx:372 Uncaught TypeError: Cannot destructure property 'config' of 'sessionWrapper' as it is undefined." error in debug console (Note that login will still fail until #1685 is done)

### CODE REVIEW

File: packages/console/src/HeapUsage.tsx [hunk 1]
```diff
@@ -41,9 +41,16 @@ function HeapUsage({
...
 
+  const isMountedRef = useIsMountedRef();
+
   const setUsageUpdateInterval = useCallback(async () => {
     try {
       const newUsage = await connection.getWorkerHeapInfo();
+
+      if (!isMountedRef.current) {
+        return;
+      }
```
Comment (mofojed) [inline packages/console/src/HeapUsage.tsx:52]: Technically this may be incorrect. E.g.
1. First pass, `monitorDuration` is `5000`, and a call to `connection.getWorkerHeapInfo()` is triggered. It is async and hasn't returned yet
2. `monitorDuration` changes to `10000`, triggering another call to `connection.getWorkerHeapInfo()`. This call returns before the call from step 1
3. Call from step 1 returns, now the data is out of date.

In practice that could never happen in this case, since the first call to `connection.getWorkerHeapInfo()` should always return before a subsequent call, but in another async situation, using the `isMountedRef` may not handle all cases.

I typically go with the `isCancelled` pattern, as that handles cases where the dependencies change, not just unmounting. An example from the React docs (looks like they name it `ignore` instead of `isCancelled` now): https://react.dev/reference/react/useEffect#fetching-data-with-effects

File: packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx [hunk 2]
```diff
@@ -368,6 +375,11 @@ export class ConsolePanel extends PureComponent<
       timeZone,
       unzip,
     } = this.props;
+
+    if (sessionWrapper == null) {
+      return null;
```
Comment (mofojed) [inline packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx:380]: We shouldn't display _nothing_ I don't think we should be displaying an error message. When do we expect this to occur?

**Review by mofojed — CHANGES_REQUESTED** [review]

File: packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx (hunk 2 above)
Comment (bmingles) [reply packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx:380]: This happens when logging out and in some cases when logging in

File: packages/console/src/HeapUsage.tsx (hunk 1 above)
Comment (bmingles) [reply packages/console/src/HeapUsage.tsx:52]: I think `monitorDuration` is how long it holds onto the history and doesn't impact the interval (unless I am missing something)

I think your appoint does apply to the interval though `isOpen ? hoverUpdateInterval : defaultUpdateInterval`. So ideally we should be cancelling if either the component unmounts `or` if the interval changes?

File: packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx (hunk 2 above)
Comment (mofojed) [reply packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx:380]: It can also happen if remote consoles are disabled. You can do that by running with the flag `deephaven.console.disable=true`, e.g.:
```
START_OPTS="-Ddeephaven.console.disable=true" ./gradlew server-jetty-app:run -Ppsk=iris
```
In this case we're displaying a blank console panel now:
image

Ideally in that scenario, we should display an error message. So I think we should display an appropriate error message here. It is still an edge case though; by default, if remote console is enabled, we won't even add a console panel to the layout. But if they already have a layout saved locally with the ConsolePanel, or they import a layout with ConsolePanel, they'll run into this error.

On Logout we immediately transition back to the login screen, so no concern about the error message appearing when logging out.

Comment (bmingles) [reply packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx:380]: @dsmmcken any suggestions on error message here?

Comment (dsmmcken) [reply packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx:380]: Is this two seperate error states?

1. "Console option is disabled."
2. "Unable to load console, no available session."

Comment (bmingles) [reply packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx:380]: Yes, although I'm not sure the user will ever actually see #2

Comment (bmingles) [reply packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx:380]: Is there a standard icon for this?

Comment (mofojed) [reply packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx:380]: Use a `LoadingOverlay` with `isLoading={null}` and the error message set, e.g.
```
      <LoadingOverlay
        isLoading={false}
        errorMessage="Console option is disabled."
      />
```

File: packages/code-studio/src/main/AppMainContainer.tsx [hunk 3]
```diff
@@ -123,7 +123,7 @@ interface AppMainContainerProps {
   match: {
     params: { notebookPath: string };
   };
-  connection: IdeConnection;
+  connection?: IdeConnection;
```
Comment (mofojed) [inline packages/code-studio/src/main/AppMainContainer.tsx:126]: Is this true? I can see `session` being `undefined`, but in what case is `connection` ever `undefined`? This shouldn't be a case we have to handle.

File: packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx [hunk 4]
```diff
@@ -368,6 +376,16 @@ export class ConsolePanel extends PureComponent<
       timeZone,
       unzip,
     } = this.props;
+
+    if (sessionWrapper == null) {
+      return (
+        <LoadingOverlay
+          isLoading={false}
+          errorMessage="Console option is disabled."
```
Comment (mofojed) [inline packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx:384]:
```suggestion
          errorMessage="Console is disabled."
```

**Review by mofojed — CHANGES_REQUESTED** [review]
`getDashboardSessionWrapper` currently only returns `SessionWrapper` - that needs to be updated to allow `undefined` as well.

File: packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx (hunk 4 above)
Comment (bmingles) [reply packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx]: fixed

File: packages/code-studio/src/main/AppMainContainer.tsx (hunk 3 above)
Comment (mofojed) [reply packages/code-studio/src/main/AppMainContainer.tsx:126]: Ah true. Should update that type in redux as well then.

Comment (bmingles) [reply packages/code-studio/src/main/AppMainContainer.tsx:126]: I think it is already up to date? `dashboardData: Record<string, DashboardData>;` can also be an empty record.

Comment (mofojed) [reply packages/code-studio/src/main/AppMainContainer.tsx:126]: Ah whoops I was looking at old code, looks good.

**Review by mofojed — APPROVED** [review]
