### PR TITLE
fix: Goto Value Skips Rows on String Column, Displays Incorrect Filter, and `shift+enter` Doesn't go to Previous

### LINKED ISSUE #1156: DH-14483 Go to value skips valid rows
Referencing JIRA DH-14483

in code-studio, execute the simple query;

```
t = emptyTable(1000000).update("A=`a`+ii", "Int=ii")
```

open the “Go to value” bar. do a search for “A” “Contains” “a2”. while still in the “a2” box, press enter. we would expect the following rows to be selected for each “enter”;

```
a2
a20
a21
a22
a23
a24
... etc
```

but it seems that valid matching rows are being skipped

### PR DESCRIPTION
**Pull request by Zhou-Ziheng**
fixes #1156, #1157

### CODE REVIEW

**Review by mofojed — CHANGES_REQUESTED** [review]

File: packages/components/src/MaskedInput.tsx [hunk 1]
```diff
@@ -386,7 +389,9 @@ const MaskedInput = React.forwardRef<HTMLInputElement, MaskedInputProps>(
         );
         return;
       }
-
+      if (key === 'Enter') {
+        onSubmit?.(event);
```
Comment (mofojed) [inline packages/components/src/MaskedInput.tsx:393]: Need `return` after this

**Review by mofojed — CHANGES_REQUESTED** [review]

File: packages/iris-grid/src/GotoRow.tsx [hunk 2]
```diff
@@ -100,11 +102,11 @@ function GotoRow({
     }
   };
 
-  const handleGotoValueKeyDown = (e: KeyboardEvent<HTMLInputElement>) => {
+  const handleGotoValueKeySubmit = (e: KeyboardEvent<HTMLInputElement>) => {
```
Comment (mofojed) [inline packages/iris-grid/src/GotoRow.tsx:105]: Could use `useCallback` here

**Review by mofojed — APPROVED** [review]
