### PR TITLE
fixed copy cell unformatted not working in Long cells

### LINKED ISSUE #660: Copy Cell/Copy Cell Unformatted not working
The "Copy Cell" and "Copy Cell Unformatted" actions are not working for me in DHC Version 0.14.1. Have tried with String, long, and int columns.

I get this error when I right-click on a cell (`long`) of a Table and click "Copy Cell":

```
Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at Function.value (ContextActionUtils.ts:119:32)
    at n.value (IrisGrid.tsx:1782:26)
    at Object.action (IrisGridContextMenuHandler.tsx:523:22)
    at n.value (ContextMenu.tsx:506:18)
    at onClick (ContextMenuItem.tsx:22:25)
    at Object.He (react-dom.production.min.js:52:317)
    at Ye (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at Er (react-dom.production.min.js:100:68)
    at Lr (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at Pe (react-dom.production.min.js:292:189)
    at react-dom.production.min.js:50:57
    at Ir (react-dom.production.min.js:105:469)
    at Jt (react-dom.production.min.js:75:265)
    at Qt (react-dom.production.min.js:74:124)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ki (react-dom.production.min.js:122:325)
    at Me (react-dom.production.min.js:292:48)
    at Zt (react-dom.production.min.js:73:352)
```

and this from "Copy Cell Unformatted" (only difference is IrisGridContextMenuHandler line number):

```
react-dom.production.min.js:101 Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at Function.value (ContextActionUtils.ts:119:32)
    at n.value (IrisGrid.tsx:1782:26)
    at Object.action (IrisGridContextMenuHandler.tsx:532:22)
    at n.value (ContextMenu.tsx:506:18)
    at onClick (ContextMenuItem.tsx:22:25)
    at Object.He (react-dom.production.min.js:52:317)
    at Ye (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at Er (react-dom.production.min.js:100:68)
    at Lr (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at Pe (react-dom.production.min.js:292:189)
    at react-dom.production.min.js:50:57
    at Ir (react-dom.production.min.js:105:469)
    at Jt (react-dom.production.min.js:75:265)
    at Qt (react-dom.production.min.js:74:124)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ki (react-dom.production.min.js:122:325)
    at Me (react-dom.production.min.js:292:48)
    at Zt (react-dom.production.min.js:73:352)
```

### PR DESCRIPTION
**Pull request by SparkyFnay**
This potentially Fixes #660 
I was not able to reproduce the error, so I cannot verify that this resolved the issue. I tried reproducing using chrome/safari on `localhost:4000`, `localhost:10000/ide`, as well as the demo app on our website.

However, looking at the error stack trace, it seems that navigator.clipboard is returning undefined in some cases, thus when we call the writeText function, the error is thrown. 
I tried added a check for navigator.clipboard === undefined so that it goes straight to the fallback copy function.

### CODE REVIEW

**Comment by dsmmcken** [comment]
Maybe it was something to do with localhost and http?

https://stackoverflow.com/a/65996386

**Comment by SparkyFnay** [comment]
@dsmmcken I saw that stackoverflow question as well, but I'm not sure how I can mock an unsafe origin. There is the `Insecure origins treated as secure` flag in chrome, but no `secure origins treated as insecure`

**Comment by mofojed** [comment]
Not going to approve until we get some more details from Raffi and/or we can reproduce the issue.

File: packages/components/src/context-actions/ContextActionUtils.ts [hunk 1]
```diff
@@ -116,6 +116,11 @@ class ContextActionUtils {
    * @returns Promise Resolved on success, rejected on failure
    */
   static copyToClipboard(text: string): Promise<void> {
+    const { clipboard } = navigator;
```
Comment (mofojed) [inline packages/components/src/context-actions/ContextActionUtils.ts:119]: This works - I think you could also write this function as an async function and it would be a little cleaner:

```typescript
  static async copyToClipboard(text: string): Promise<void> {
    try {
      await navigator.clipboard.writeText(text);
    } catch (e) {
      ContextActionUtils.copyToClipboardExecCommand(text)
    }
  }
```

**Review by mofojed — APPROVED** [review]

**Comment by mofojed** [comment]
I was able to reproduce through @rbasralian's VPN
