### PR TITLE
fix: sorting frozen columns

### LINKED ISSUE #1645: Freezing a column then sorting columns in the organize column results in wrong column frozen
**Description**

Freezing a column then sorting columns in the organize column results in wrong column frozen. After the user is also unable to unfreeze the wrongly frozen column.

**Steps to reproduce**

```
from deephaven import time_table

simple_ticking = time_table("PT00:00:01").update([
        "MyString=new String(`a`+i)",
        "MyInt=new Integer(i)",
        "MyLong=new Long(i)",
        "MyDouble=new Double(i+i/10)",
        "MyFloat=new Float(i+i/10)",
        "MyBoolean=new Boolean(i%2==0)",
        "MyChar= new Character((char) ((i%26)+97))",
        "MyShort=new Short(Integer.toString(i%32767))",
        "MyByte= new java.lang.Byte(Integer.toString(i%127))"])
```

1. Right click the "MyFloat" column header, and select "Freeze column" from the context menu.
2. Open the table overflow menu, and select organize columns, then press the sort ascending button
3. (optional): attempt to unfreeze the frozen column (now MyBoolean)

**Expected results**
MyFloat remains frozen, and the other columns are sorted.

**Actual results**

MyBoolean becomes the frozen column, and no columns are shown as frozen as the organize columns list. Right clicking the "MyBoolean" column doesn't give an option to unfreeze it, only freeze which then freezes a completely different column.

**Additional details and attachments**

freeze_column

**Versions**

Engine Version: 0.31.0
Web UI Version: 0.54.0
Java Version: 21.0.1
Barrage Version: 0.6.0

### PR DESCRIPTION
**Pull request by wusteven815**
- Fixes #1645 
  - Moves are now generated for frozen columns (like front/end for initial moved columns) and only used when sorting
  - The range being sorted is truncated to remove frozen/front/end columns
- Added tests to make sure the sort is correct

### CODE REVIEW

**Review by mofojed — COMMENTED** [review]
I just want to confirm with @dsmmcken - do we want the frozen columns to be sorted as well when you click sort? My instinct is no, we want the frozen columns to stay in the same order they were frozen in.

File: packages/iris-grid/src/sidebar/visibility-ordering-builder/VisibilityOrderingBuilder.tsx [hunk 1]
```diff
@@ -635,11 +635,47 @@ class VisibilityOrderingBuilder extends PureComponent<
...
+    for (let i = 0; i < model.frozenColumns.length; i += 1) {
+      const frozenColumn = model.frozenColumns[i];
+      // get index of frozenColumn
+      let frozenIndex = 0;
+      for (let j = 0; j < model.columns.length; j += 1) {
+        if (model.columns[j].name === frozenColumn) {
+          frozenIndex = j;
+          break;
+        }
+      }
```
Comment (mofojed) [inline packages/iris-grid/src/sidebar/visibility-ordering-builder/VisibilityOrderingBuilder.tsx:654]: Can use `getColumnIndexByName`:
```
const frozenIndex = model.getColumnIndexByName(frozenColumn.name);
```

File: packages/iris-grid/src/sidebar/visibility-ordering-builder/VisibilityOrderingBuilder.tsx [hunk 2]
```diff
@@ -635,11 +635,47 @@ class VisibilityOrderingBuilder extends PureComponent<
...
+        }
+        // placed in front, increase index
+        if (to < frozenIndex) frozenIndex += 1;
+      }
+      if (frozenIndex !== i) {
+        initialAndFrozenMovedColumns.push({
+          from: frozenIndex,
+          to: i,
+        });
+      }
```
Comment (mofojed) [inline packages/iris-grid/src/sidebar/visibility-ordering-builder/VisibilityOrderingBuilder.tsx:672]: You can use `GridUtils.getVisibleIndex(frozenIndex, initialAndFrozenMovedColumns)` instead of re-creating the algorithm.

**Review by mofojed — CHANGES_REQUESTED** [review]

**Review by mofojed — APPROVED** [review]
