### PR TITLE
Fix the objects not being loaded with console

### LINKED ISSUE #405: Console table dropdown doesnt populate on opening DHC console from existing session
Steps to reproduce:

1. Start deephaven core, open a browser window to connect
2. Create a new table of some kind
3. Open a new browser tab and connect to the same server
4. Click the console table/widget pickers and try to see existing objects
image

Expected:
The existing tables will be available there.

Actual:
The menus are grayed out, no options are available.

Workaround:
Open the Panels menu instead, and select the missing objects from there.

### PR DESCRIPTION
**Pull request by mofojed**
- In Community, ConsolePanel is always loaded, so remove transition/isLoaded flags
- Keep track of objects in the ConsolePanel and pass it into Console
Fixes #405

### CODE REVIEW

File: packages/dashboard-core-plugins/src/panels/ConsolePanel.jsx [hunk 1]
```diff
@@ -96,6 +98,29 @@ class ConsolePanel extends PureComponent {
...
+
+  subscribeToFieldUpdates() {
+    const { sessionWrapper } = this.props;
+    const { session } = sessionWrapper;
+
+    this.objectSubscriptionCleanup = session.connection.subscribeToFieldUpdates(
+      updates => {
+        log.debug('Got updates', updates);
+
+        const { updated, created } = updates;
```
Comment (vbabich) [inline packages/dashboard-core-plugins/src/panels/ConsolePanel.jsx:112]: Should we handle deletion as well?

File: packages/console/src/Console.jsx [hunk 2]
```diff
@@ -453,6 +457,11 @@ export class Console extends PureComponent {
     });
   }
 
+  updateObjectMap() {
+    const { objectMap } = this.props;
+    this.setState({ objectMap });
```
Comment (vbabich) [inline packages/console/src/Console.jsx:462]: `objectMap` is optional according to `PropTypes`. Either do `{ objectMap: new Map(objectMap) }` here or update `PropTypes` (then drop `new Map()` in the `constructor` too to match `updateObjectMap`)

**Review by vbabich — CHANGES_REQUESTED** [review]

File: packages/dashboard-core-plugins/src/panels/ConsolePanel.jsx (hunk 1 above)
Comment (mofojed) [reply packages/dashboard-core-plugins/src/panels/ConsolePanel.jsx]: Good call, that's my bad. Fixed

**Review by vbabich — APPROVED** [review]
