### PR TITLE
fix: DH-17076 LayoutHints on TreeTables were not being applied

### LINKED ISSUE #2035: Column grouping layout hints are ignored on rollup tables
A customer noticed that column groupings from layout hints are respected on regular tables, but ignored on rollup tables. (The columns can be grouped manually afterward and it works; the issue is just the layout hints being ignored.)

DH-17076

Only reproducible in Groovy:

```java
import io.deephaven.engine.util.LayoutHintBuilder

source = emptyTable(100).update(
    "K1 = ii",
    "K2 = K1 % 10",
    "Y = randomDouble(0, 10)",
    "Z = randomDouble(0, 10)",
)

result_norollup = source.setLayoutHints(LayoutHintBuilder.get().columnGroup("MyCols", ["Y", "Z"]).build())

import io.deephaven.api.agg.spec.AggSpec
import io.deephaven.api.agg.Aggregation


result_rollup = source
    .rollup([Aggregation.of(AggSpec.avg(), "Y", "Z")], false, "K2")
    .setLayoutHints(LayoutHintBuilder.get().columnGroup("MyCols", ["Y", "Z"]).build())
```

For some reason, `layout_hints` is not an available method on `RollupTable` in Python: https://github.com/deephaven/deephaven-core/blob/dbf2b2db31ac3e982fc6c432b66d3cb688fda431/py/server/deephaven/table.py#L169

### PR DESCRIPTION
**Pull request by mofojed**
- Related to DH-17076
- Needed a Core patch: https://github.com/deephaven/deephaven-core/pull/5555
- Tested using both the Groovy snippet from the ticket
- Fixes #2035

### CODE REVIEW

File: packages/iris-grid/src/IrisGridTreeTableModel.ts [hunk 1]
```diff
@@ -230,6 +230,12 @@ class IrisGridTreeTableModel extends IrisGridTableModelTemplate<
     return [this.virtualColumns.length, this.groupedColumns.length];
   }
 
+  get layoutHints(): DhType.LayoutHints | null | undefined {
+    // TODO: Update this when JS API types are updated with this.
+    // eslint-disable-next-line @typescript-eslint/no-explicit-any
+    return (this.table as any).layoutHints;
```
Comment (mattrunyon) [inline packages/iris-grid/src/IrisGridTreeTableModel.ts:236]: Should we feature detect here? If this had to be added to the DHC JSAPI then it's probably not part of the DHE JSAPI

Although since it's just 1 level deep it shouldn't throw and should just return undefined like it would have before

**Review by mattrunyon — CHANGES_REQUESTED** [review]
Did you want to merge the DHC change before merging this? Or order shouldn't matter?

Also, did you want to put the Jira ticket in the title so we know when it goes into DHE?

File: packages/iris-grid/src/IrisGridTreeTableModel.ts (hunk 1 above)
Comment (mofojed) [reply packages/iris-grid/src/IrisGridTreeTableModel.ts:236]: Yea you're right, I should be checking here.

**Comment by mofojed** [comment]
@mattrunyon order shouldn't matter here, I added feature detection as well.

File: packages/iris-grid/src/IrisGridTreeTableModel.ts [hunk 2]
```diff
@@ -231,9 +240,10 @@ class IrisGridTreeTableModel extends IrisGridTableModelTemplate<
   }
 
   get layoutHints(): DhType.LayoutHints | null | undefined {
-    // TODO: Update this when JS API types are updated with this.
-    // eslint-disable-next-line @typescript-eslint/no-explicit-any
-    return (this.table as any).layoutHints;
+    if (isLayoutTreeTable(this.table)) {
+      return this.table.layoutHints;
+    }
+    return undefined;
```
Comment (mattrunyon) [inline packages/iris-grid/src/IrisGridTreeTableModel.ts:246]: I realized it shouldn't really matter since DHE would just return undefined for `this.table.layoutHints`. But still not bad to feature detect it.

**Review by mattrunyon — CHANGES_REQUESTED** [review]
Just 2 small things

File: packages/iris-grid/src/IrisGridTreeTableModel.test.ts [hunk 3]
```diff
@@ -27,3 +27,48 @@ describe('IrisGridTreeTableModel', () => {
...
+
+  test('layoutHints property does not exist should not crash', () => {
+    const columns = irisGridTestUtils.makeColumns();
+    const table = irisGridTestUtils.makeTreeTable(columns, columns, 100, []);
+    // eslint-disable-next-line @typescript-eslint/no-explicit-any
+    delete (table as any).layoutHints;
+    const model = new IrisGridTreeTableModel(dh, table);
+
+    expect(model.layoutHints).toEqual(undefined);
+  });
```
[the remark this answers is not in the document]
Comment (mofojed) [reply packages/iris-grid/src/IrisGridTreeTableModel.test.ts:73]: Not quite. `undefined` vs. property not existing, it is technically different. e.g.

```javascript
var o = { foo: 'bar', fiz: undefined }
var o2 = { ...o }
delete o2.fiz

console.log(o.hasOwnProperty('fiz')) // true
console.log(o2.hasOwnProperty('fiz')) //false
```

File: packages/iris-grid/src/IrisGridTreeTableModel.ts (hunk 2 above)
Comment (mofojed) [reply packages/iris-grid/src/IrisGridTreeTableModel.ts:246]: Yea my thoughts as well

**Review by mattrunyon — APPROVED** [review]
