### PR TITLE
fix: Made selector return types generic

### LINKED ISSUE #1687: Redux selector return types should be generic
**Description**

The `getSettings` and `getWorkspace` return types should be derived from the generic `State extends RootState` arg to support DHE consumption.

**Versions**
0.56

### PR DESCRIPTION
**Pull request by bmingles**
fixes #1687

### CODE REVIEW

File: packages/utils/src/TypeUtils.ts [hunk 1]
```diff
@@ -27,6 +27,13 @@ export type OnlyOneProp<T> = {
   [P in keyof T]: { [ONEPROP in P]: T[ONEPROP] };
 }[keyof T];
 
+/**
+ * Remove `Partial` wrapper from a type. Note that this is slightly different
+ * than `Required` because it will preserve optional properties on the original
+ * target type.
+ */
+export type UndoPartial<T> = T extends Partial<infer U> ? U : never;
```
Comment (mofojed) [inline packages/utils/src/TypeUtils.ts:35]: Ohh neat

**Review by mofojed — APPROVED** [review]
