### PR TITLE
fix: stuck to bottom on filter clear

### LINKED ISSUE #1477: isStuckToBottom behaviour when filtering
**Description**

Given a table and a scroll position at the top of the table, filtering to a result of less than a full viewport, then clearing the filter sets the table to isStuckToBottom (and further, only applies after a re-render). As a user this can be confusing and frustrating that you end up at the bottom of a table after the filter clears.

Although, this may be the desired behaviour if the user was already at the bottom. Open to heuristic suggestions for this behaviour. Maybe isStuckToBottom isn't triggered until on short viewports until it a tick actually goes past the end of the screen.

In comparison, if you are at the top, filter by a result that has a full viewport worth of results (example filter MyBoolean = true from below), then clear that filter you remain at the top. So behaviour is inconsistent.

**Steps to reproduce**

1. Create a simple table
```
from deephaven import empty_table

simple_static = empty_table(1000).update([
        "MyString=new String(`a`+(char) ((i%3)+97))",
        "MyInt=new Integer(i)",
        "MyLong=new Long(i % 3)",
        "MyDouble=new Double(i+i/10)",
        "MyFloat=new Float(i+i/10)",
        "MyBoolean=new Boolean(i%2==0)",
        "MyChar= new Character((char) ((i%26)+97))",
        "MyShort=new Short(Integer.toString(i%32767))",
        "MyByte= new java.lang.Byte(Integer.toString(i%127))"])
```
2. From a scroll position at the top of the table, filter the table to 1 result (filter by MyInt = 0)
3. Clear the filter with a shortcut (ctrl/cmd+e)
4. Move the mouse anywhere over the table to trigger a re-render

**Expected results**

I feel like I would expect the table to be back at the top.

**Actual results**

The table is stuck to the bottom. (It doesn't move until after step 4, which is even weirder).

**Versions**

Engine Version: 0.27.0
Web UI Version: 0.46.0
Java Version: 17.0.7
Barrage Version: 0.6.0

### PR DESCRIPTION
**Pull request by ethanalvizo**
Closes #1477 

Previous comments are in #1571 PR. 

Note: Once this PR is merged #1571 can go in as well

### CODE REVIEW

File: packages/grid/src/Grid.tsx [hunk 1]
```diff
@@ -1314,26 +1323,52 @@ class Grid extends PureComponent<GridProps, GridState> {
...
+    } else if (
+      event instanceof KeyboardEvent ||
+      (event && 'nativeEvent' in event) // used to catch the case that a synthetic react keyboard event is passed
+    ) {
+      isUserInputDown =
+        event.key === 'ArrowDown' ||
+        event.key === 'End' ||
+        event.key === 'PageDown';
+      isUserInputRight = event.key === 'ArrowRight';
+    }
```
Comment (mofojed) [inline packages/grid/src/Grid.tsx:1362]: I know I said to do these checks here in the last review - but this logic doesn't really belong here. `SelectionKeyHandler` has all the logic for which keys map to which direction, and arguably the logic from `handleWheel` for scrolling should be extracted to it's own mouse handler.

The reason I mention this though is because there are cases that aren't handled here - for example, if you press Shift+End, it will go to the far right instead of the bottom.

So instead of taking an event and passing it through, we really should just be passing in an option, e.g.
```
type StickyOptions = { shouldStickRight: boolean; shouldStickBottom: boolean };
setViewState(..., stickyOptions?: StickyOptions)
```

**Review by mofojed — CHANGES_REQUESTED** [review]

File: packages/grid/src/key-handlers/SelectionKeyHandler.ts [hunk 2]
```diff
@@ -279,7 +286,15 @@ class SelectionKeyHandler extends KeyHandler {
...
       false
     );
-    grid.setViewState({ top: viewportPosition });
+
+    const stickyOptions: StickyOptions = {
+      shouldStickBottom:
+        event.key === 'ArrowDown' ||
+        event.key === 'End' ||
+        event.key === 'PageDown',
+      shouldStickRight: event.key === 'ArrowRight',
```
Comment (mofojed) [inline packages/grid/src/key-handlers/SelectionKeyHandler.ts:295]: We shouldn't be doing these checks again - we're already in the `handlePageDown` method, which is triggered only on a keyboard event when navigating page down. Just do `stickOptions = { shouldStickBottom: true, shouldStickRight: false }`

File: packages/grid/src/key-handlers/SelectionKeyHandler.ts [hunk 3]
```diff
@@ -177,6 +177,13 @@ class SelectionKeyHandler extends KeyHandler {
 
       const { theme } = grid.props;
       const { autoSelectRow = false, autoSelectColumn = false } = theme;
+      const stickyOptions: StickyOptions = {
+        shouldStickBottom:
+          event.key === 'ArrowDown' ||
+          event.key === 'End' ||
+          event.key === 'PageDown',
+        shouldStickRight: event.key === 'ArrowRight',
+      };
```
Comment (mofojed) [inline packages/grid/src/key-handlers/SelectionKeyHandler.ts:186]: Similar to my other comment - we shouldn't be checking the key itself again, just look at the `deltaColumn`/`deltaRow` to set the sticky options. Also need to pass it through in the above `grid.moveCursorToPosition` call I think.

File: packages/grid/src/Grid.tsx [hunk 4]
```diff
@@ -1314,26 +1342,47 @@ class Grid extends PureComponent<GridProps, GridState> {
...
+      });
     }
     if (left != null) {
-      this.setState({ isStuckToRight: isStickyRight && left >= lastLeft });
+      this.setState({
+        isStuckToRight:
+          isStickyRight &&
+          left >= lastLeft &&
+          (stickyOptions?.shouldStickRight ?? false),
+      });
```
Comment (mofojed) [inline packages/grid/src/Grid.tsx:1385]: Perhaps I named the sticky options incorrectly. I think we only want to update the options when sticky options are `true`, we shouldn't be updating `isStuckToRight` or `isStuckToBottom` at all if the values are false. So would be more like:

```
if (top != null && (stickOptions?.shouldStickToBottom ?? false)) {
  this.setState({ isStuckToBottom: isStickBottom && top >= lastTop });
}
```

As it is right now, you'll always wipe out the `isStuckToBottom`/`isStuckToRight` state whenever the cursor is moved, even if not a result of a user interaction.

**Review by mofojed — CHANGES_REQUESTED** [review]

File: packages/grid/src/key-handlers/SelectionKeyHandler.ts (hunk 3 above)
Comment (ethanalvizo) [reply packages/grid/src/key-handlers/SelectionKeyHandler.ts:186]: Ah yes I missed that one just the very first moveCursorToPosition the other ones didn't need it

File: packages/grid/src/key-handlers/SelectionKeyHandler.ts [hunk 5]
```diff
@@ -169,21 +174,22 @@ class SelectionKeyHandler extends KeyHandler {
...
-          event.key === 'PageDown',
-        shouldStickRight: event.key === 'ArrowRight',
-      };
+      // const stickyOptions: StickyOptions = {
+      //   shouldStickBottom:
+      //     event.key === 'ArrowDown' ||
+      //     event.key === 'End' ||
+      //     event.key === 'PageDown',
+      //   shouldStickRight: event.key === 'ArrowRight',
+      // };
```
Comment (mofojed) [inline packages/grid/src/key-handlers/SelectionKeyHandler.ts:192]:
```suggestion
```

**Review by mofojed — CHANGES_REQUESTED** [review]

File: packages/grid/src/key-handlers/SelectionKeyHandler.ts [hunk 6]
```diff
@@ -169,14 +174,22 @@ class SelectionKeyHandler extends KeyHandler {
...
 
       const { theme } = grid.props;
       const { autoSelectRow = false, autoSelectColumn = false } = theme;
+      // const stickyOptions: StickyOptions = {
+      //   shouldStickBottom:
+      //     event.key === 'ArrowDown' ||
+      //     event.key === 'End' ||
+      //     event.key === 'PageDown',
+      //   shouldStickRight: event.key === 'ArrowRight',
+      // };
```
Comment (mofojed) [inline packages/grid/src/key-handlers/SelectionKeyHandler.ts:192]: Still need to delete this unused code

**Review by mofojed — CHANGES_REQUESTED** [review]

File: packages/grid/src/key-handlers/SelectionKeyHandler.ts (hunk 6 above)
Comment (ethanalvizo) [reply packages/grid/src/key-handlers/SelectionKeyHandler.ts]: Ah sorry about that I accidentally made that change on the e2e context menu branch rather than this one. Should be good to go now

**Review by mofojed — APPROVED** [review]
