### PR TITLE
fix: TablePlugin needs to know table name and selected range

### LINKED ISSUE #2093: TablePlugin needs to know current grid selection, table name
As a developer of a TablePlugin, I would like to be able to get the table name and the current selection state from within my plugin.
Previously we could do this with the `panel` prop that was passed in before it was removed: https://github.com/deephaven/web-client-ui/pull/1982
Could use `panel.getTableName()` to get the table name and `panel.irisGrid.current.state` to get the selected range of rows. Would like to still be able to do that.

### PR DESCRIPTION
**Pull request by AkshatJawne**
Resolves #2093

### CODE REVIEW

**Review by AkshatJawne — COMMENTED** [review]
@mofojed I just passed the `tableName` and `selectedRanges` props down to the plugin, was there anything specific you were wanting here, in terms of a "better way" to handle the prop?

File: packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx [hunk 1]
```diff
@@ -423,11 +423,6 @@ export class IrisGridPanel extends PureComponent<
         return null;
       }
 
-      // TODO #2093: Find a better way to handle deprecated panel prop
-      const deprecatedProps = {
-        panel: this,
-      };
-
```
Comment (mofojed) [inline packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx:430]: Let's continue to leave this in for now - now that there's a replacement, they have a version to replace the deprecated properties with the new options we're providing.

**Review by mofojed — CHANGES_REQUESTED** [review]

**Review by AkshatJawne — COMMENTED** [review]
Ready for re-review @mofojed

**Review by mofojed — APPROVED** [review]
