### PR TITLE
Fix column tooltip error when side menu is opened

### LINKED ISSUE #626: Column tooltip error when opening side menu
**Description**

When opening the table side menu if a column tooltip is active, iris grid throws an error at an assertion for IrisGrid.tsx:3396 which is for `shownColumnTooltipX`

**Steps to reproduce**
1. Open styleguide
2. On the iris-grid example, hover over the rightmost column
3. Move cursor slightly over to the menu button and click

**Expected results**

Menu opens

**Actual results**

Grid goes to an error state

**Additional details and attachments**

The issue occurs because the tooltip position is not in metrics since it is fully obscured when the menu opens. The iris-grid TS conversion added several assertions which throw errors we may have just been eating before

https://user-images.githubusercontent.com/8619789/176206814-4698bd4a-59d1-4bf3-bcd6-bc69bcd177a5.mov

**Versions**
 - Deephaven: 0.14

### PR DESCRIPTION
**Pull request by mattrunyon**
Fixes #626 

We could modify the hover handler to know where the button is, but this fix seems easier/more robust to future issues

### CODE REVIEW

File: packages/iris-grid/src/IrisGrid.tsx [hunk 1]
```diff
@@ -3170,6 +3170,106 @@ export class IrisGrid extends Component<IrisGridProps, IrisGridState> {
     }
   );
 
+  getColumnTooltip = memoize(
```
Comment (dsmmcken) [inline packages/iris-grid/src/IrisGrid.tsx:3173]: Does model/metrics return new objects making this memorize correctly?

**Review by mofojed — DISMISSED** [review]

**Comment by dsmmcken** [comment]
Nice, this originally had an onLeave and I removed it to handle the case when the popper is above the grid, this is better.
